package by.home.project.controller;

public enum CommandName {
	SIGNIN, 
	SIGNOUT, 
	REGISTRATION, 
	CHANGELOCALE, 
	GOTOSIGNINPAGE, 
	GOTOMAINPAGE, 
	GOTOREGISTRATIONPAGE, 
	GOTOCATALOGPAGE,
	GETGOODSLIST, 
	GOTOBASKETPAGE,
	GOTOERRORPAGE,
	PUTINTOBASKET,  
	DELFROMBASKET, 
	GOTOUSERINFOPAGE, 
	SHOWGOODSPAGE
}
